### ISSUE TITLE
Ability to parse JSON with arbitrary keys

### ISSUE THREAD

**Issue by jaredculp** [davidfstr/trycast#19]
Is it possible to enforce the presence of certain keys but ignore all others? My use case is parsing JSON payloads from an event bus where I want to ignore fields that may be present but that I don't care to include in the `TypedDict`.

This functionality would be similar to json-schema's `additionalProperties: true` keyword.

For example:
```python
from typing import TypedDict, NotRequired
from trycast import trycast

class MyType(TypedDict):
    a: str
    b: NotRequired[str | None]

# currently fails validation because "c" is in the dict
trycast(MyType, {"a": "foo", "b": "bar", "c": "baz"})
```

**Comment by davidfstr** [comment]
I'm about to be on vacation for a week so I won't have any bandwidth to work on this feature myself in the short term.

@jaredculp if you (or anyone else) is interested in making a PR, I may be able to get it merged more quickly (before I leave on Saturday).

**Comment by jaredculp** [comment]
I can take a crack at it, but I'm having a hard time getting a dev environment set up:

```
Installing dependencies from lock file

Package operations: 26 installs, 0 updates, 0 removals

  • Installing pyyaml (6.0)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  running egg_info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/Users/jaredculp/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/jaredculp/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/jaredculp/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
      self.find_sources()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
      mm.run()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
      super().add_defaults()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 204, in get_source_files
    File "/var/folders/ty/q_gqmw4d1fd9j5_tlg5j3n7c0000gn/T/tmp89pxv7f6/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  

  at ~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==6.0)"'.
```

**Comment by jaredculp** [comment]
@davidfstr happy to try!

Can't get a working dev environment set up on my mac (also tried docker):
```
 > [5/6] RUN poetry install:
#9 3.106       145│
#9 3.106       146│             if error is not None:
#9 3.106     → 147│                 raise error from None
#9 3.106       148│
#9 3.106       149│             return path
#9 3.106       150│
#9 3.106       151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
#9 3.106
#9 3.106 Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517
"pyyaml (==6.0)"'.
```

**Comment by davidfstr** [comment]
> AttributeError: cython sources
---
> "pyyaml (==6.0)"'.

You're probably running into [this issue](https://github.com/yaml/pyyaml/issues/601) where cpython 3 broke the build process of PyYAML 5.x

Try this:
```
poetry shell
pip3 install "Cython<3.0" "pyyaml<6" --no-build-isolation
poetry install
```

**Comment by davidfstr** [comment]
The ability to parse JSON with extra keys that are not in the original TypedDict definition will be in trycast 1.1.0, when it is released, probably in a day or two.

**Comment by davidfstr** [comment]
TypedDicts generally allow extra keys because of subclassing. For example the following typechecks without error in mypy:

```python
from typing import TypedDict, NotRequired
from trycast import trycast

class MyType(TypedDict):
    a: str
    b: NotRequired[str | None]

class MyTypeSubclass(TypedDict):
    a: str
    b: NotRequired[str | None]
    c: str

d1: MyTypeSubclass = {"a": "foo", "b": "bar", "c": "baz"}
d2: MyType = d1  # OK
```

Since `d2` is treated by mypy as a valid `MyType` then `trycast(MyType, d2)` should succeed.

**Comment by phormio** [comment]
I withdraw my 2 comments. Sorry to have wasted your time.

I think I was misreading the specification. In particular, I now see that my 2 quotes from the specification were not applicable to the situation I applied them to.
